### ISSUE TITLE
Decide on subdomain

### ISSUE THREAD

**Issue by gaearon** [reactjs/cn.reactjs.org#1]
Should it be `cn`, `zh`, `zh-cn`, `zh-hans`, or something else?

**Comment by zhongdeming428** [comment]
I prefer `cn` as the subdomain,just like https://cn.bing.com/?mkt=zh-CN

**Comment by gaearon** [comment]
What if somebody later wants to start a Traditional Chinese translation?

**Comment by chenjie3323** [comment]
Can i have a try

**Comment by robertying** [comment]
Something like Wikipedia's:

- Simplified Chinese (Mainland) `https://zh.wikipedia.org/zh-cn/`
- Traditional Chinese (Hong Kong) `https://zh.wikipedia.org/zh-hk/`
- Traditional Chinese (Macao) `https://zh.wikipedia.org/zh-mo/`
- Simplified Chinese (Malaysia) `https://zh.wikipedia.org/zh-my/`
- Simplified Chinese (Singapore) `https://zh.wikipedia.org/zh-sg/`
- Traditional Chinese (Taiwan) `https://zh.wikipedia.org/zh-tw/`

Well, I don't think we can achieve all these variants for now, but using `zh-cn` for Simplified Chinese and `zh-tw` for Traditional Chinese seems conventional.

**Comment by QC-L** [comment]
I think it would be better to use cn.
Traditional Chinese translation use zh-hant.

**Comment by shaodahong** [comment]
yeh, better to use cn

**Comment by haimengzhang** [comment]
using `zh-cn` for simplified and `zh-tw` for traditional is more intuitive as I see it more often. second @robertying, but that being said, `zh-cn`  is a child category of `zh-hans`, and `zh-tw` of`zh-hant`, with the parent categories meaning Chinese written simplified scripts or traditional scripts.

**Comment by gaearon** [comment]
The problem is we **can’t have two languages on one domain**. This would make the website more complex. So we need to choose two different domains.

**Comment by gaearon** [comment]
cc @chloewlin, any thoughts?

**Comment by chloewlin** [comment]
@gaearon I agree. I also prefer `cn` for Simplified and `tw` for Traditional for its clarify and simplicity.

**Comment by shaodahong** [comment]
@QC-L i understand your worry, but weibo also use `tw.weibo.com`

**Comment by QC-L** [comment]
weibo use https://weibo.com/tw, not `tw.weibo.com`

**Comment by discountry** [comment]
@gaearon @chloewlin Using `cn` and `tw` would cause political issues to the whole React project. 

We should avoid that, it's not wise to do so.

BTW, if we use `cn` and `tw` , we also need `hk`, that would make a simple problem to a complex one.

**Comment by gaearon** [comment]
I wasn’t aware of the political implications. Sorry about this!

Do `zh-tw` and `zh-cn` have any issues too?

**Comment by haimengzhang** [comment]
How about zh-cn as a domain for simplified and zh-tw for traditional? Are
we not going to have two subdomains? @gaearon

**Comment by shaodahong** [comment]
agree, political issues are important

**Comment by gaearon** [comment]
Also, Vue docs go with `cn` — is that problematic too in a way?

**Comment by gaearon** [comment]
@haimengzhang

If `zh-cn` and `zh-tw` aren’t problematic they sound ok to me as subdomains.

**Comment by discountry** [comment]
@gaearon Vue only has one Chinese doc.

**Comment by shaodahong** [comment]
maybe use `cn` and `zh-tw`

**Comment by haimengzhang** [comment]
Sounds good to me. Tw and cn is indeed a very sensitive issue😅

**Comment by shaodahong** [comment]
like facebook `https://zh-tw.facebook.com/`

**Comment by haimengzhang** [comment]
Hmm i think however we use it, it will be a bit political. Say just the
choice of not choosing zh-hk instead of zh-tw. Western media and countries
like US take Taiwan as a country, but China is on the opposite stance. So
either way, the choice of picking tw has some political flavor.

**Comment by chloewlin** [comment]
I am fine with `zh-tw` if it helps us stay away from potential controversies and stay focused on producing quality, up-to-date translations that help React docs accessible to more developers. Thank you everyone for your thoughtful reminders.

**Comment by gaearon** [comment]
Can tw be `zh-hant` then?

**Comment by haimengzhang** [comment]
Yes, that sounds most neutral of all.

**Comment by gaearon** [comment]
The other concern is typing. If it’s too long, it could be annoying and alienating. I don’t know how many websites in practice use two/five/seven letter codes.

Is `zh-tw` controversial or is it only `tw`?

I think `zh-cn` and `zh-tw` could be a good tradeoff overall between typing and accuracy. But I don’t know if those are considered problematic in any way.

**Comment by chenjie3323** [comment]
I don't think the developer will notice it. they are focusing their works. For me,  `zh-tw` and `zh-cn` are not problematic. BTW, I'm a Chinese developer.

**Comment by discountry** [comment]
@gaearon 

zh-CN | 中文(简体)
-- | --
zh-HK | 中文(香港)
zh-MO | 中文(澳门)
zh-SG | 中文(新加坡)
zh-TW | 中文(繁体)

The majority uses simplified Chinese, so we could keep the `cn` for simplified Chinese version doc.

And `zh-tw` is just a language code, it's not sensitive. We can use it for traditional one.

Simplified Chinese and Traditional Chinese are not just different characters, we use different phrases and words, so I think we need to spread the two translation in two repos.

Let's try to make this simple and efficient, do not make a small problem turn into a bigger one.

**Comment by shaodahong** [comment]
The focus on language, not country

**Comment by gaearon** [comment]
Thanks everyone for your perspectives. I’ll consult more people and learn more about this issue and then will post our proposal later today. I agree that we need to be efficient and not spend too much time on this. But on the other hand I want to make sure we’ve done due diligence here and don’t cause unnecessary controversy. I’ll post later!

**Comment by shaodahong** [comment]
`cn` for simplified and `zh-tw` for traditional make easy

**Comment by hijiangtao** [comment]
Maybe we need more discussion about how to handle the subdomain for Traditional Chinese Translation, but it seems pretty clear currently, which is `cn` is well known in representing Simplified Chinese Translation.

I quickly look through some famous repositories and here's what I found:

* Angular for https://angular.cn/
* Vue for https://cn.vuejs.org/
* Redux for https://cn.redux.js.org/
* Mapbox for https://www.mapbox.cn/
* Mobx for https://cn.mobx.js.org/
* RxJS for https://cn.rx.js.org/

There's a bunch of cases.

**Comment by gaearon** [comment]
I agree with the proposal to use `cn` for the Simplified Chinese docs. It seems to be commonly accepted in the front-end community and uncontroversial in this discussion. 
 
I will need more time to choose the Traditional Chinese domain. I’ll post in this thread after we have done so, but for now this shouldn’t need to stop us from work. We haven’t set up a repo for it anyway yet. 

Thank you all again! This was very helpful.

**Comment by gaearon** [comment]
After talking to people on different sides of this issue, we've decided to use the neutral script codes to avoid any appearance of the political stance. We don't intend to host multiple dialects of Traditional and Chinese translations, so `zh-hans` and `zh-hant` will be sufficient.

We could possibly add redirects from shorter domains in the future if enough people complain about it. But for now I think this is sufficient and addresses the issue. Thanks again to everyone for sharing your opinions and concerns.
